// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// A platform-agnostic platform-specific options for initializing Firebase.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // For web platform
    return web;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYFtifrvaJb7p-jnKD9AdCvqGZ8opz7iI',
    appId: '1:240680865775:android:ca24d4821d348ad0c1701a',
    messagingSenderId: '240680865775',
    projectId: 'final-assignment-1e6d8',
    storageBucket: 'final-assignment-1e6d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYFtifrvaJb7p-jnKD9AdCvqGZ8opz7iI',
    appId: '1:240680865775:ios:ca24d4821d348ad0c1701a',
    messagingSenderId: '240680865775',
    projectId: 'final-assignment-1e6d8',
    storageBucket: 'final-assignment-1e6d8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYFtifrvaJb7p-jnKD9AdCvqGZ8opz7iI',
    appId: '1:240680865775:windows:ca24d4821d348ad0c1701a',
    messagingSenderId: '240680865775',
    projectId: 'final-assignment-1e6d8',
    storageBucket: 'final-assignment-1e6d8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYFtifrvaJb7p-jnKD9AdCvqGZ8opz7iI',
    appId: '1:240680865775:web:ca24d4821d348ad0c1701a',
    messagingSenderId: '240680865775',
    projectId: 'final-assignment-1e6d8',
    storageBucket: 'final-assignment-1e6d8.firebasestorage.app',
  );
}
